ENDPOINT = 'http://localhost:8070'
GET_ALL_URL = '/rule/query'
INSERT_URL = '/rule/doInsertRule'
UPDATE_URL = '/rule/doUpdateObject'
DELETE_URL = '/rule/deleteRuleId'
SECRET_KEY = 'secret123'
LOGFILE = 'app.log'